import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mohammad Sahil | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Layout>
        <div className='center_content'>
          Center Content
        </div>
      </Layout>
    </>
  )
}
